name: Destroy Notes API

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
      TF_VAR_region: ${{ secrets.TF_VAR_region }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
      PROJECT_ID: ${{ secrets.TF_VAR_project_id }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.TF_VAR_project_id }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - name: Cleanup stale state lock
        run: |
          LOCK_PATH="gs://${PROJECT_ID}-tfstate/notes-api/default.tflock"
          if gcloud storage ls "$LOCK_PATH" >/dev/null 2>&1; then
            echo "Deleting stale lock file..."
            gcloud storage rm "$LOCK_PATH"
          else
            echo "No stale lock found."
          fi
      - run: terraform init -input=false
      - run: terraform destroy -auto-approve
