name: Destroy Notes API

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    env:
      TF_VAR_project_id: ${{ secrets.TF_VAR_project_id }}
      TF_VAR_region: ${{ secrets.TF_VAR_region }}
      TF_VAR_db_password: ${{ secrets.TF_VAR_db_password }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - run: terraform init -input=false
      - run: terraform destroy -auto-approve
